# Generated by Django 4.2.2 on 2023-07-06 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='THD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('THD_number', models.IntegerField()),
                ('ip', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Номер ТСД',
                'verbose_name_plural': 'Номер ТСД',
            },
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 16, 37, 14, 884839)),
        ),
        migrations.AlterField(
            model_name='flaw',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 16, 37, 14, 884839), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='flaw',
            name='decision',
            field=models.BooleanField(blank=True),
        ),
    ]
