# Generated by Django 4.2.2 on 2023-08-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='visualization_z',
            field=models.IntegerField(default=3000),
        ),
    ]
