# Generated by Django 4.2.2 on 2023-07-31 07:46

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='article_list',
        ),
        migrations.AddField(
            model_name='specification',
            name='nomenclatures',
            field=models.ManyToManyField(to='main.nomenclature', verbose_name='Содержимое спецификации'),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='article',
            field=models.CharField(max_length=250, primary_key=True, serialize=False, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='mass',
            field=models.FloatField(blank=True, null=True, verbose_name='Масса одного изделия'),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='maximum',
            field=models.FloatField(blank=True, null=True, verbose_name='Максимум продукции'),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='minimum',
            field=models.FloatField(blank=True, null=True, verbose_name='Минимум продукцииё'),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='units',
            field=models.CharField(max_length=20, verbose_name='Единицы измерения'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='production_time',
            field=models.TimeField(verbose_name='Время производства'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='storage_name',
            field=models.CharField(max_length=60, validators=[main.validators.validate_no_spaces]),
        ),
        migrations.AddConstraint(
            model_name='nomenclature',
            constraint=models.CheckConstraint(check=models.Q(('units__exact', 'кг'), ('units__exact', 'шт'), _connector='OR'), name='Значение единиц измерения необходимо указывать в килограммах или штуках в формате кг или шт'),
        ),
        migrations.AddConstraint(
            model_name='nomenclature',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('units__exact', 'шт'), ('mass__isnull', False)), ('units__exact', 'кг'), _connector='OR'), name='Если изделие измеряется поштучно необходимо указать массу одного изделия'),
        ),
    ]
