# Generated by Django 4.2.2 on 2023-07-06 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_thd_alter_deliverynote_datetime_alter_flaw_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thd',
            name='is_using',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 22, 19, 38, 804762)),
        ),
        migrations.AlterField(
            model_name='flaw',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 22, 19, 38, 804762), primary_key=True, serialize=False),
        ),
    ]
