# Generated by Django 4.2.2 on 2023-08-09 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_storage_visualization_z'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flaw',
            name='id',
        ),
        migrations.RemoveField(
            model_name='flaw',
            name='worker_add',
        ),
        migrations.CreateModel(
            name='RejectionAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('article_list', models.TextField(blank=True, null=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.worker')),
            ],
            options={
                'verbose_name': 'Акт выбраковки',
                'verbose_name_plural': 'Акты выбраковки',
            },
        ),
        migrations.AddField(
            model_name='flaw',
            name='rejection_act',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.rejectionact'),
        ),
    ]
