# Generated by Django 4.2.2 on 2023-08-01 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_specification_article_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='visualization_x',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='visualization_y',
        ),
    ]
