# Generated by Django 4.2.2 on 2023-08-01 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_nomenclature_article_alter_nomenclature_mass_and_more'),
        ('main', '0002_remove_specification_article_list_and_more'),
    ]

    operations = [
    ]
