# Generated by Django 4.2.2 on 2023-07-06 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_thd_is_using_alter_deliverynote_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thd',
            name='username',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 22, 28, 24, 849261)),
        ),
        migrations.AlterField(
            model_name='flaw',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 22, 28, 24, 849261), primary_key=True, serialize=False),
        ),
    ]
