# Generated by Django 4.2.2 on 2023-08-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_merge_20230801_0937'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='nomenclature',
            name='Значение единиц измерения необходимо указывать в килограммах или штуках в формате "кг" или "шт"',
        ),
        migrations.AddField(
            model_name='storage',
            name='visualization_x',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='storage',
            name='visualization_y',
            field=models.IntegerField(default=20),
        ),
    ]
