# Generated by Django 4.2.2 on 2023-07-06 19:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_thd_username_alter_deliverynote_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thd',
            name='username',
        ),
        migrations.AddField(
            model_name='thd',
            name='worker_id',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.RESTRICT, to='main.worker'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 22, 31, 24, 371512)),
        ),
        migrations.AlterField(
            model_name='flaw',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 22, 31, 24, 371512), primary_key=True, serialize=False),
        ),
    ]
