# Generated by Django 4.2.2 on 2023-07-06 19:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_thd_username_thd_worker_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynote',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 22, 33, 26, 94219)),
        ),
        migrations.AlterField(
            model_name='flaw',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 22, 33, 26, 94219), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='thd',
            name='worker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.worker'),
        ),
    ]
