# Generated by Django 4.2.2 on 2023-08-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenclature',
            name='comment',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
