# Generated by Django 4.2.2 on 2023-07-07 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_deliverynote_datetime_alter_flaw_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenclature',
            name='mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='mass',
            field=models.PositiveIntegerField(default=700),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 18, 6, 57, 197634)),
        ),
        migrations.AlterField(
            model_name='flaw',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 18, 6, 57, 198135), primary_key=True, serialize=False),
        ),
    ]
