# Generated by Django 4.2.2 on 2023-07-07 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_nomenclature_mass_storage_mass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynote',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 18, 25, 42, 216132)),
        ),
        migrations.AlterField(
            model_name='flaw',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 18, 25, 42, 216132), primary_key=True, serialize=False),
        ),
    ]
