# Generated by Django 4.2.2 on 2023-07-12 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_thd_is_comp_alter_deliverynote_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thd',
            old_name='worker_id',
            new_name='worker',
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 12, 10, 43, 35, 566100)),
        ),
        migrations.AlterField(
            model_name='flaw',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 12, 10, 43, 35, 568110), primary_key=True, serialize=False),
        ),
    ]
