# Generated by Django 4.2.2 on 2023-07-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_deliverynote_datetime_alter_flaw_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='adress',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
