# Generated by Django 4.2.2 on 2023-07-17 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_storage_adress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='crate_list',
        ),
        migrations.AddField(
            model_name='crates',
            name='cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.storage'),
        ),
    ]
