# Generated by Django 4.2.2 on 2023-07-17 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_storage_crate_list_crates_cell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crates',
            name='cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='crates', to='main.storage'),
        ),
    ]
