# Generated by Django 4.2.2 on 2023-07-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_crates_cell'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='provider',
            field=models.CharField(default='', max_length=150),
        ),
    ]
