# Generated by Django 4.2.2 on 2023-07-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_deliverynote_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclature',
            name='maximum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='minimum',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
