# Generated by Django 4.2.2 on 2023-07-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_nomenclature_maximum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverynote',
            name='number',
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='id',
            field=models.CharField(default='', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
