# Generated by Django 4.2.2 on 2023-07-18 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_deliverynote_number_deliverynote_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crates',
            name='size',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='thd',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.worker'),
        ),
    ]
