# Generated by Django 4.2.2 on 2023-07-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_crates_size_alter_thd_worker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverynote',
            old_name='worker_id',
            new_name='worker',
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='article_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
