# Generated by Django 4.2.2 on 2023-07-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_worker_id_deliverynote_worker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crates',
            name='text_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
