# Generated by Django 4.2.2 on 2023-07-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_crates_text_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crates',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
