# Generated by Django 4.2.2 on 2023-07-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_crates_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crates',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
