# Generated by Django 4.2.2 on 2023-07-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_crates_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='size_left',
            field=models.FloatField(blank=True),
        ),
    ]
