# Generated by Django 4.2.2 on 2023-07-25 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_storage_size_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='size_left',
        ),
    ]
