# Generated by Django 4.2.2 on 2023-07-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_storage_size_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclature',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
