# Generated by Django 4.2.2 on 2023-07-25 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_nomenclature_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempCrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_id', models.CharField(blank=True, max_length=15, null=True)),
                ('amount', models.FloatField()),
                ('size', models.CharField(max_length=80)),
                ('crate', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.crates')),
            ],
            options={
                'verbose_name': 'Временная коробка',
                'verbose_name_plural': 'Временные коробки',
            },
        ),
    ]
