# Generated by Django 4.2.2 on 2023-07-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_tempcrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='number',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
