# Generated by Django 4.2.2 on 2023-07-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_deliverynote_number_alter_deliverynote_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionstorage',
            name='article',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
