# Generated by Django 4.2.2 on 2023-07-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_deliverynote_number_alter_deliverynote_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionstorage',
            name='article',
        ),
        migrations.AddField(
            model_name='productionstorage',
            name='title',
            field=models.CharField(default='', max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='productionstorage',
            name='units',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='nomenclature',
            name='units',
            field=models.CharField(max_length=20),
        ),
    ]
