# Generated by Django 4.2.2 on 2023-07-26 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_productionstorage_article'),
        ('main', '0029_remove_productionstorage_article_and_more'),
    ]

    operations = [
    ]
