# Generated by Django 4.2.2 on 2023-07-26 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_merge_20230726_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionstorage',
            name='article',
        ),
    ]
