# Generated by Django 4.2.2 on 2023-07-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_remove_productionstorage_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='x_cell_coord',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storage',
            name='x_cell_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storage',
            name='y_cell_coord',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storage',
            name='y_cell_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storage',
            name='z_cell_coord',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storage',
            name='z_cell_size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
