# Generated by Django 4.2.2 on 2023-08-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('title', models.CharField(max_length=120, verbose_name='Название плана')),
                ('datetime', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'План',
                'verbose_name_plural': 'Планы',
            },
        ),
    ]
