# Generated by Django 4.2.2 on 2023-07-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('title', models.CharField(max_length=120)),
                ('datetime', models.DateTimeField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'План',
                'verbose_name_plural': 'Планы',
            },
        ),
    ]
